# Import BaseModel for API responses
from pydantic import BaseModel, Field


# ==========================================
# Upload API Response
# ==========================================

class UploadResponse(BaseModel):
    message: str
    files_uploaded: int
    filenames: list[str]


# ==========================================
# Document Page
# Represents one page extracted from a PDF
# ==========================================

class DocumentPage(BaseModel):
    page_number: int = Field(..., description="Page number in the PDF")
    text: str = Field(..., description="Extracted text from the page")


# ==========================================
# Document Chunk
# Represents one chunk of text that will be
# embedded and stored in ChromaDB.
# ==========================================

class DocumentChunk(BaseModel):
    document_name: str = Field(..., description="Original PDF filename")

    page_number: int = Field(..., description="Page number where this chunk came from")

    chunk_index: int = Field(..., description="Chunk number within the document")

    text: str = Field(..., description="Chunk text")

    embedding: list[float] | None = Field(
        default=None,
        description="Embedding vector generated by the embedding model"
    )


# ==========================================
# Chat Request
# ==========================================

class ChatRequest(BaseModel):
    question: str


# ==========================================
# Source Citation
# ==========================================

class SourceReference(BaseModel):
    document_name: str
    page_number: int


# ==========================================
# Chat Response
# ==========================================

class ChatResponse(BaseModel):
    answer: str
    sources: list[SourceReference]